nerf_type: mip  # Select NeRF type.

vanila:
  dataset:
    scene_name: lego  # Select scene type.

  trainer:
    device_ids: [0]  # Cuda GPU ids. ex) [0, 1] for 2 GPUs.
    batch_size: 2048  # Reduce when OOM.
    max_iter: 50000
    num_cameras_each_iter: 50
    initial_lr: 0.0005
    final_lr: 0.00005
    coarse_fine_loss_lambda: 1.0
    validate_for_every: 10
    save_ckpt_for_every: 10

  renderer:
    num_coarse_samples: 64
    num_fine_samples: 128
    near_dist: 2.0
    far_dist: 6.0
    bounding_volume_size: 1.5
    num_gif_frames: 100  # 50 ~ 300 recommended.
    weight_filtering_alpha: null
    render_type: albedo

  encoder:
    spatial_encoding_l: 16
    directional_encoding_l: 4

mip:
  dataset:
    scene_name: lego  # Select scene type.
  
  trainer:
    device_ids: [0]  # Cuda GPU ids. ex) [0, 1] for 2 GPUs.
    batch_size: 2048  # Reduce when OOM.
    max_iter: 50000
    num_cameras_each_iter: 50
    initial_lr: 0.0005
    final_lr: 0.000005
    coarse_fine_loss_lambda: 0.1
    validate_for_every: 10
    save_ckpt_for_every: 10

  renderer:
    num_coarse_samples: 128
    num_fine_samples: 128
    near_dist: 2.0
    far_dist: 6.0
    bounding_volume_size: 1.5
    num_gif_frames: 50  # 50 ~ 300 recommended.
    weight_filtering_alpha: 0.01
    render_type: albedo

  encoder:
    spatial_encoding_l: 16
    directional_encoding_l: 4
